### ISSUE TITLE
How is this different from https://github.com/aws-ia/terraform-aws-eks-blueprints-addons

### ISSUE THREAD

**Issue by creisor** [aws-ia/terraform-aws-eks-blueprints-addon#18]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

There are two repos in `aws-ia` with very similar names:
aws-ia/terraform-aws-eks-blueprints-addons
and
aws-ia/terraform-aws-eks-blueprints-addon

These repos seem to provide similar offerings. For those of us trying to upgrade from the pre-V5 EKS Blueprints, this is extremely confusing in an already-confusing process.

When should this be used over the plural version (`addons` vs `addon`)?

#### Provide a link to the example/module related to the question

[This really just applies to the entire repo](https://github.com/aws-ia/terraform-aws-eks-blueprints-addon)

#### Additional context

This guide might eventually be helpful (and does seem to point to the [plural one](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons)), but it is incomplete: https://aws-ia.github.io/terraform-aws-eks-blueprints/main/v4-to-v5/addons/

**Comment by lassizci** [comment]
Was wondering the same when creating a new cluster and having used v4 earlier. Following https://aws-ia.github.io/terraform-aws-eks-blueprints/main/v4-to-v5/motivation/#v5x-structure

> terraform-aws-eks-blueprints-addon  # Module for creating Terraform based addon (IRSA + Helm chart)
> terraform-aws-eks-blueprints-addons # Will contain a select set of addons supported by the EKS Blueprints

Would use the `addon` when there's a helm chart, that needs `irsa` - or if there's specific reason I want to manage the helm chart via terraform rather than e.g via GitOps tool.

**Comment by creisor** [comment]
Ah! Thanks for finding that.

**Comment by bryantbiggs** [comment]
I would love to understand more about what is confusing between the two projects 
- https://github.com/aws-ia/terraform-aws-eks-blueprints-addon
- https://github.com/aws-ia/terraform-aws-eks-blueprints-addons

We have examples in both projects in the READMEs, descriptions on each repository, as well as test cases - please share any details as to what parts are confusing or not clear in terms of their purpose, intent, or usage

**Comment by creisor** [comment]
So am I understanding it correctly that `addon` (singular) is a template for adding any helm chart in the world, whereas `addons` (plural) is a more curated set of helm charts?

As for what is confusing about the two projects:
* Both repositories have the exact same name, with a single character difference (the letter `s`)
* They are both terraform modules
* One is described as `Terraform module to deploy Kubernetes addons on Amazon EKS clusters`, and the other `Terraform module which provisions an addon (Helm release) and an IAM role for service accounts (IRSA)` -- those read pretty much the same to me

At this point in the journey of upgrading from v4 to v5 of the blueprints, you might be a bit vexed. And as always when dealing with AWS, you are probably suffering from a bit of acronym fatigue. You've taken apart the engine and now you're trying to find the pictures to remind you how to put it back together again.

I apologize if I am acting like an idiot. Perhaps I was wrong to assume that others might be confused by all this.

**Comment by bryantbiggs** [comment]
Does the provided documentation and examples not help disambiguate the intent and purpose of each module?

**Comment by creisor** [comment]
> Does the provided documentation and examples not help disambiguate the intent and purpose of each module?

That is correct.

So am I understanding it correctly that `addon` (singular) is a template for adding any helm chart in the world, whereas `addons` (plural) is a more curated set of helm charts?

**Comment by creisor** [comment]
I think the change in https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/be4455257046a1ceb47b71f4b1508db3f5843638 sufficiently addresses this issue. Thank you!

**Comment by bryantbiggs** [comment]
Apologies, I forgot to come back to this

> So am I understanding it correctly that addon (singular) is a template for adding any helm chart in the world, whereas addons (plural) is a more curated set of helm charts?

Yes to the 2nd part. The singular version is module to create one addon using any helm chart available, and it supports IRSA as well (if needed). We use this in the addons (plural) for the select addons we support. So you can think of the singular form as the building block to the plural form

Also, the addons (plural) does provide the means to pass in any number of helm charts that you would like to deploy with the module https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/61ca8c13091d6ac1a53eda88b5ef4d88a17859bd/tests/complete/main.tf#L209-L210 - this does not support IRSA though, since thats harder to map correctly. What most folks should be using is the addons (plural)
