### ISSUE TITLE
Attributes that cannot be determined until apply

### ISSUE THREAD

**Issue by tanvp112** [aws-ia/terraform-aws-eks-blueprints-addon#22]
## Description

v1.1.1 changed has introduced the famous terraform constraint:

```
...in data "aws_iam_policy_document" "this":
196:   count = local.create_policy && length(local.perms) > 0 ? 1 : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict
│ how many instances will be created. To work around this, use the -target argument to first apply only the resources
│ that the count depends on.
```

`local.perms` performs concat with 3 passed in policies, but the data object is trying to determine the final policy as soon as `plan` is called. 

Reverted to v1.1.0 to avoid this issue at the moment.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by bryantbiggs** [comment]
Please provide a reproduction so we can help triage or troubleshoot

**Comment by joaocc** [comment]
Hi. 
I'm also facing the same issue, and ink this particular case this is being called from https://github.com/aws-ia/terraform-aws-eks-blueprints-addons (namely, aws_efs_csi_driver). @bryantbiggs, I can also confirm this started to happen after upgrading to v1.1.1, and that it doesn't happen with the other addons I am deploying (external-dns, external-secrets, velero).

As for repro, cannot reproduce the full environment, but I can try to provide a config from aws_efs_csi_driver.
From other cases where I got this message, it seems to happen whenever a try() is involved in the elements that are used in keys, which can happen upstream in the call stack

**Comment by bryantbiggs** [comment]
@joaocc can you please provide a repo

**Comment by joaocc** [comment]
Hi. Not sure if I will be able to due to the way we have our environment (large terragrunt setup, not running terraform standalone). Sorry @bryantbiggs 

@tanvp112 could you please indicate more details about the context calling the addon (singular) module?

Trying to diagnose a bit more my case, where this is being called from a fork of addons (plural), which can prob help in identifying some changes which don't cause the error.
```
│ Error: Invalid count argument
│ 
│   on .terraform/modules/this_addon__aws_efs_csi_driver.aws_efs_csi_driver/main.tf line 195, in data "aws_iam_policy_document" "this":
│  195:   count = local.create_policy && length(local.perms) > 0 ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.

│ Error: Invalid count argument
│ 
│   on .terraform/modules/this_addon__cluster_autoscaler.cluster_autoscaler/main.tf line 195, in data "aws_iam_policy_document" "this":
│  195:   count = local.create_policy && length(local.perms) > 0 ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.
```

However I noticed that v1.1.1 also changed some of the same lines that appear in this error:
https://github.com/aws-ia/terraform-aws-eks-blueprints-addon/compare/v1.1.0...v1.1.1
```
  count = local.create_policy ? 1 : 0
  count = local.create_policy && length(local.perms) > 0 ? 1 : 0
```
and these
```
account_id = try(data.aws_caller_identity.current[0].account_id, "*")
partition  = try(data.aws_partition.current[0].partition, "*")
```

This seems to be a consequence of trying to deal with the cases where var.create_role is false.
However, although I was originally looking at this as source of the error, looking at the error message seems to point that the cause might be another change which seems to be unrelated:
```
  perms       = concat(var.source_policy_documents, var.override_policy_documents, var.policy_statements)
```

With this in mind, and considering I am using a fork of the addons (plural), there are also some changes on how these policies are constructed (and some end up having try() or lookup() in there).
https://github.com/kit-ar/aws-ia--terraform-aws-eks-blueprints-addons/compare/kit-ar/aws-4x/v1.9.1004...aws-ia:terraform-aws-eks-blueprints-addons:v1.9.1?expand=1

Any thoughts on this?

**Comment by joaocc** [comment]
with regards to the change stemming from the data elements, since both `local.account_id` and `local.partition` are only used in one place, which is already under `count` for the same condition as the `data` elements, if we expand `data.aws_caller_identity.current[0].account_id` and `data.aws_partition.current[0].partition` only on the line they are needed in, then we don't need try() or lookup() as they will only be expanded if count=1

**Comment by joaocc** [comment]
on the other hand, this doesn't seem to have any impact on the line where the error is reported, so prob not worth pursuing.

**Comment by bryantbiggs** [comment]
it will be very difficult, almost impossible, to help without a reproduction

**Comment by bryantbiggs** [comment]
per Hashicorp, you should not use `depends_on` across modules since this will knowingly cause issues https://github.com/hashicorp/terraform/issues/30340#issuecomment-1010202582

In 99% of the cases I've come across, `depends_on` is not necessary and should be avoid as much as possible

**Comment by joaocc** [comment]
quick analysis of the case of our implementation of cluster_autoscaler: the only value coming from dependency module (this_eks) are the following vars `cluster_name, cluster_endpoint, cluster_version, oidc_provider_arn`.
